### ISSUE TITLE
实测下拉刷新卡顿，应该是 setData 过于频繁造成的

### ISSUE THREAD

**Issue by 1c7** [the-liuchao/RefreshDemo#3]
如题。只是顺带一说，不是在要求什么。我继续找别的实现方法去了。
依然感谢开源，起码是个思路。元旦快乐。

**Comment by bytebubbles** [comment]
> 如题。只是顺带一说，不是在要求什么。我继续找别的实现方法去了。
> 依然感谢开源，起码是个思路。元旦快乐。

你找到别的方法了吗，自定义下拉都会卡顿，bindtouchmove获取的数值都不连续的

**Comment by 1c7** [comment]
@SpringerInFighting 我看了另外2个微信小程序（暗号和猫搭），他们也都是用微信自带的下拉刷新。
后来我觉得非得弄自定义下拉刷新太折腾了，没有什么好的思路（不用频繁 setData 的思路）
所以我也不折腾了，算了，就用默认的下拉刷新。
